// Generates src/generated/references.ts with explicit file imports so Bun embeds every
// reference document into the compiled binary. Run after adding files to references/.
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';

const files = readdirSync('references')
  .filter((f) => f.toLowerCase().endsWith('.idml'))
  .sort();
const lines = [
  '// Generated by scripts/gen-assets.ts — do not edit by hand. Run `bun run gen`.',
  '',
  ...files.map((f, i) => `import ref${i} from '../../references/${f}' with { type: 'file' };`),
  '',
  'export const BUNDLED_REFERENCES: { name: string; file: string; path: string }[] = [',
  ...files.map(
    (f, i) =>
      `  { name: ${JSON.stringify(f.replace(/\.idml$/i, ''))}, file: ${JSON.stringify(f)}, path: ref${i} },`,
  ),
  '];',
  '',
];
const out = 'src/generated/references.ts';
const content = lines.join('\n');
const check = process.argv.includes('--check');
if (check) {
  const current = existsSync(out) ? readFileSync(out, 'utf8') : '';
  if (current !== content) {
    console.error(`${out} is out of date. Run: bun run gen`);
    process.exit(1);
  }
  console.log(`${out} is up to date (${files.length} references)`);
} else {
  writeFileSync(out, content);
  console.log(`wrote ${out} (${files.length} references)`);
}
