// Generates src/generated/references.ts with explicit file imports so Bun embeds every
// reference document into the compiled binary. Run after adding files to references/.
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';

const files = readdirSync('references')
  .filter((f) => f.toLowerCase().endsWith('.idml'))
  .sort();
const lines = [
  '// Generated by scripts/gen-assets.ts — do not edit by hand. Run `bun run gen`.',
  '',
  ...files.map((f, i) => `import ref${i} from '../../references/${f}' with { type: 'file' };`),
  '',
  'export const BUNDLED_REFERENCES: { name: string; file: string; path: string }[] = [',
  ...files.map(
    (f, i) =>
      `  { name: ${JSON.stringify(f.replace(/\.idml$/i, ''))}, file: ${JSON.stringify(f)}, path: ref${i} },`,
  ),
  '];',
  '',
];
const out = 'src/generated/references.ts';
const content = lines.join('\n');
const check = process.argv.includes('--check');
if (check) {
  const current = existsSync(out) ? readFileSync(out, 'utf8') : '';
  if (current !== content) {
    console.error(`${out} is out of date. Run: bun run gen`);
    process.exit(1);
  }
  console.log(`${out} is up to date (${files.length} references)`);
} else {
  writeFileSync(out, content);
  console.log(`wrote ${out} (${files.length} references)`);
}

// ---- schemas: embed every RNG file of the newest schema version(s) ----------------------------
import { statSync } from 'node:fs';

const schemaRoot = 'schemas/idml';
const versions = readdirSync(schemaRoot).filter(
  (v) => /^\d+(\.\d+)?$/.test(v) && statSync(`${schemaRoot}/${v}`).isDirectory(),
);
const embedVersions = process.env.INDESIGN_MCP_EMBED_ALL_SCHEMAS
  ? versions
  : versions.sort((a, b) => Number(b) - Number(a)).slice(0, 1);
const schemaLines = ['// Generated by scripts/gen-assets.ts — do not edit by hand. Run `bun run gen`.', ''];
const entries: string[] = [];
let n = 0;
for (const v of embedVersions.sort()) {
  const walk = (dir: string, prefix: string) => {
    for (const f of readdirSync(dir).sort()) {
      const p = `${dir}/${f}`;
      if (statSync(p).isDirectory()) walk(p, `${prefix}${f}/`);
      else if (f.endsWith('.rng')) {
        schemaLines.push(`import s${n} from '../../${p}' with { type: 'file' };`);
        entries.push(
          `  { version: ${JSON.stringify(v)}, file: ${JSON.stringify(`${prefix}${f}`)}, path: s${n} },`,
        );
        n++;
      }
    }
  };
  walk(`${schemaRoot}/${v}`, '');
}
schemaLines.push(
  '',
  'export const BUNDLED_SCHEMAS: { version: string; file: string; path: string }[] = [',
  ...entries,
  '];',
  '',
);
const schemaOut = 'src/generated/schemas.ts';
const schemaContent = schemaLines.join('\n');
if (check) {
  const current = existsSync(schemaOut) ? readFileSync(schemaOut, 'utf8') : '';
  if (current !== schemaContent) {
    console.error(`${schemaOut} is out of date. Run: bun run gen`);
    process.exit(1);
  }
  console.log(`${schemaOut} is up to date (${n} schema files)`);
} else {
  writeFileSync(schemaOut, schemaContent);
  console.log(`wrote ${schemaOut} (${n} schema files from versions ${embedVersions.join(', ')})`);
}
